# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
package = load_json(json_path: "../package.json")

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :deploy do
    increment_version_number(
      version_number: package['version']
    )
    increment_build_number(
      xcodeproj: "FatBuck.xcodeproj",
      build_number: package['build']
    )
    build_app(
      workspace: "FatBuck.xcworkspace", 
      scheme: "FatBuck",
      export_xcargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight
  end
end
